Remove dbg_read_internal_state()
It's never had a definition anyway and the namespacing/deprecation
process was now causing a compile error in debug/fuzzing builds for me w/ GCC:

src/fuzzers/libzeek_fuzzer_shared.so: error: undefined reference to 'zeek::detail::dbg_read_internal_state()'